name: my first workflow

on:
  push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: welcome message
        run: echo "This is my first GitHub Actions Workflow Job"
      - name: list files
        run: ls
      - name: Read file
        run: cat README.md

